### ISSUE TITLE
Add a config to configure the appearance of objects

### ISSUE THREAD

**Issue by Paradox75831004** [CaiganMythFang/caigan_lethal_expansion_projects#1]
Due to the fact that there are many items in the assembly, she wins in conjunction with others, because she spams her own items more than others. Therefore, I would like a config to configure the appearance of objects and adjust their value at will.

**Comment by Roobotics** [comment]
@Paradox75831004 not many extra scrap mods let you adjust their spawn rates, and many packs intentionally spawn higher than vanilla scrap just so it shows up less frequently, try something like 'Balanced_Items' mod if you're wanting to tweak spawns per-moon or values. It's very useful for those things.

**Comment by CaiganMythFang** [comment]
As of v1.6.0 there is now a config that is generated after you run the mod the first time, which lets you set the spawn weights of every scrap item in the mod.

**Comment by Roobotics** [comment]
Oop, in that case I stand corrected! I've played with your scrap mod a few times now, and didn't even notice it generated a config afterwards. (too many mods)
